import { allSetups, saveSetup, removeSetup, replaceAll, readDraft, saveDraft as persistDraft, clearDraft } from './db.js';

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const choices = {
  session:['Asia','London','New York','London/NY overlap','Other'], direction:['Long','Short'], scenario:['Continuation','Reversal','Breakout/displacement','Rejection','Other','Unknown'],
  locations:['VWAP','Band 1','D-VAH','D-VAL','W-VAH','W-VAL','D-POC','W-POC','P-W-POC','Other'], relation:['Price ↑ / CVD ↑','Price ↑ / CVD ↓','Price ↓ / CVD ↓','Price ↓ / CVD ↑','Price ↔ / CVD ↑','Price ↔ / CVD ↓','Other'],
  structure:['HH','HL','LH','LL','Break upward','Break downward','Range','Unclear'], trdTimeframe:['None','1m','3m','5m','Other'], trdDirection:['None','Up','Down'], trdType:['Normal','Large bubble','Sweep + reaction','Other','Unknown'], result:['NO TRADE','WIN','LOSS','BE']
};
let setups=[], filter='All', editingId=null, photos=[], toastTimer, draftTimer;
const draftKey='xau-library-draft-v1';
function notify(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}
function isoInput(value=new Date()){const d=new Date(new Date(value).getTime()+5*60*60*1000);return d.toISOString().slice(0,16)}
function pkt(value){try{return new Intl.DateTimeFormat('en-PK',{timeZone:'Asia/Karachi',dateStyle:'medium',timeStyle:'short'}).format(new Date(value))+' PKT'}catch{return value||'—'}}
function bucket(value){const n=Math.abs(Number(value));if(!Number.isFinite(n))return '—';if(n<5000)return '0–5k';if(n<10000)return '5–10k';if(n<20000)return '10–20k';if(n<50000)return '20–50k';return '50k+'}
function nav(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='stats')renderStats();if(view==='library')renderLibrary();window.scrollTo({top:0,behavior:'smooth'})}
function selectOptions(items,value=''){return `<option value="">Select…</option>${items.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('')}`}
function field(label,name,type='text',value='',opts={}){let control=type==='select'?`<select name="${name}" ${opts.required?'required':''}>${selectOptions(opts.items,value)}</select>`:type==='textarea'?`<textarea name="${name}" placeholder="${opts.placeholder||''}">${esc(value)}</textarea>`:`<input name="${name}" type="${type}" value="${esc(value)}" placeholder="${opts.placeholder||''}" ${opts.step?`step="${opts.step}"`:''} ${opts.min!==undefined?`min="${opts.min}"`:''} ${opts.required?'required':''}>`;return `<div class="field ${opts.full?'full':''}"><label>${label}${opts.required?' *':''}</label>${control}</div>`}
function checks(name,items,selected=[]){return `<div class="chips">${items.map((x,i)=>`<label class="chip-check"><input type="checkbox" name="${name}" value="${esc(x)}" ${selected.includes(x)?'checked':''}><span>${esc(x)}</span></label>`).join('')}</div>`}
async function renderForm(existing=null){let draftRecord=null;if(!existing){try{draftRecord=await readDraft()}catch{}}editingId=existing?.id||null;photos=existing?.screenshots?[...existing.screenshots]:(draftRecord?.screenshots||[]);$('#form-title').textContent=existing?'Edit setup':'New setup';
 const legacyDraft=!existing?JSON.parse(localStorage.getItem(draftKey)||'null'):null;const draft=draftRecord?.values||legacyDraft;const v=existing||draft||{};const trade=v.trade||{},cvd=v.cvd||{},structure=v.structure||{},trd=v.trd||{},notes=v.notes||{};
 $('#setup-form').innerHTML=`<div class="section"><h2 class="section-title">Setup details</h2><div class="form-grid">${field('Captured at (PKT)','capturedAt','datetime-local',existing?isoInput(existing.capturedAt):(draft?.capturedAt||isoInput(new Date())),{required:true})}${field('Instrument','instrument','text',v.instrument||'XAUUSD',{required:true})}${field('Session','session','select',v.session,{items:choices.session,required:true})}${field('Direction','direction','select',v.direction,{items:choices.direction,required:true})}${field('Scenario','scenario','select',v.scenario,{items:choices.scenario,required:true})}</div></div>
 <div class="section"><h2 class="section-title">Locations</h2>${checks('locations',choices.locations,v.locations||[])}<div class="field other-field ${v.locations?.includes('Other')?'':'hidden'}" id="location-other-wrap"><input name="locationOther" placeholder="Describe the location" value="${esc(v.locationOther||'')}"></div></div>
 <div class="section"><h2 class="section-title">Price + CVD</h2><div class="form-grid">${field('Raw CVD','cvdRaw','number',cvd.raw??'',{step:'any',placeholder:'Original value'})}<div class="field"><label>CVD bucket</label><p class="calc-note" id="cvd-bucket">${bucket(cvd.raw)}</p></div>${field('Price / CVD relationship','relationship','select',cvd.relationship,{items:choices.relation,required:true})}${field('15m CVD structure','cvdStructure','select',structure.cvd,{items:choices.structure})}${field('15m Price structure','priceStructure','select',structure.price,{items:choices.structure})}</div></div>
 <div class="section"><h2 class="section-title">TRD / Bubble</h2><div class="form-grid">${field('Timeframe','trdTimeframe','select',trd.timeframe||'None',{items:choices.trdTimeframe})}${field('Direction','trdDirection','select',trd.direction||'None',{items:choices.trdDirection})}${field('Type','trdType','select',trd.type,{items:choices.trdType})}${field('Score / points (optional)','score','number',v.score??'',{step:'any'})}</div></div>
 <div class="section"><h2 class="section-title">Trade plan</h2><div class="form-grid">${field('Entry','entry','number',trade.entry??'',{step:'any'})}${field('Stop','stop','number',trade.stop??'',{step:'any'})}${field('Target','target','number',trade.target??'',{step:'any'})}<div class="field"><label>Planned RR</label><p class="calc-note" id="planned-rr">${plannedRR(trade)}</p></div>${field('Result','result','select',trade.result,{items:choices.result})}${field('Result in R','resultR','number',trade.resultR??'',{step:'any',placeholder:'e.g. 1.5'})}</div></div>
 <div class="section"><h2 class="section-title">Notes</h2><div class="form-grid">${field('What I saw','saw','textarea',notes.saw,{full:true,placeholder:'Price action, structure, context…'})}${field('Why I entered','why','textarea',notes.why,{full:true})}${field('What happened','happened','textarea',notes.happened,{full:true})}${field('What I learned','learned','textarea',notes.learned,{full:true})}</div></div>
 <div class="section"><h2 class="section-title">Screenshots</h2><div class="photo-drop"><label class="photo-pick"><b>＋ Add screenshots</b><span>Images stay on this device · multiple allowed</span><input id="photo-input" type="file" accept="image/*" multiple capture="environment"></label><div class="previews" id="previews"></div></div></div>
 <div class="form-actions"><button class="primary" type="submit">${existing?'Save changes':'Save setup'}</button>${existing?'<button type="button" class="secondary danger-text" id="delete-setup">Delete</button>':''}</div>`;
 updatePreviews();const form=$('#setup-form');form.addEventListener('input',onFormInput);form.addEventListener('change',onFormInput);form.addEventListener('submit',submitSetup);$('#photo-input').addEventListener('change',addPhotos);if(existing)$('#delete-setup').addEventListener('click',()=>deleteCurrent(existing.id));$('#cvd-bucket').textContent=bucket(cvd.raw);toggleOther();
}
function plannedRR(t){if([t.entry,t.stop,t.target].some(x=>x===''||x==null))return '—';const e=Number(t.entry),s=Number(t.stop),target=Number(t.target),risk=Math.abs(e-s);return [e,s,target].every(Number.isFinite)&&risk>0?`${(Math.abs(target-e)/risk).toFixed(2)}R`:'—'}
function onFormInput(e){if(e.target.name==='cvdRaw')$('#cvd-bucket').textContent=bucket(e.target.value);if(['entry','stop','target'].includes(e.target.name))$('#planned-rr').textContent=plannedRR(Object.fromEntries(new FormData($('#setup-form'))));toggleOther();if(e.type==='input'||e.target.matches('input,textarea,select'))saveDraft()}
function toggleOther(){$('#location-other-wrap')?.classList.toggle('hidden',!$$('input[name="locations"]:checked').some(x=>x.value==='Other'))}
function saveDraft(immediate=false){const form=$('#setup-form');if(!form)return;const values=Object.fromEntries(new FormData(form));values.locations=$$('input[name="locations"]:checked',form).map(x=>x.value);try{localStorage.setItem(draftKey,JSON.stringify(values))}catch{}clearTimeout(draftTimer);const save=()=>persistDraft({values,screenshots:photos}).catch(()=>{});if(immediate)save();else draftTimer=setTimeout(save,250)}
async function addPhotos(event){for(const file of event.target.files){if(!file.type.startsWith('image/'))continue;const resized=await resizeImage(file);photos.push({name:file.name,type:resized.type,blob:resized,addedAt:new Date().toISOString()})}event.target.value='';updatePreviews();saveDraft(true)}
async function resizeImage(file){if(file.size<4_000_000)return file;try{const bmp=await createImageBitmap(file);const scale=Math.min(1,2400/Math.max(bmp.width,bmp.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bmp.width*scale);canvas.height=Math.round(bmp.height*scale);canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);return await new Promise(r=>canvas.toBlob(r,'image/jpeg',.88))||file}catch{return file}}
function updatePreviews(){const el=$('#previews');if(!el)return;el.innerHTML=photos.map((p,i)=>`<div class="preview"><img src="${URL.createObjectURL(p.blob)}" alt="Screenshot ${i+1}"><button type="button" data-remove-photo="${i}" aria-label="Remove screenshot">×</button></div>`).join('');$$('[data-remove-photo]',el).forEach(b=>b.onclick=()=>{photos.splice(Number(b.dataset.removePhoto),1);updatePreviews();saveDraft()})}
function formPayload(){const f=$('#setup-form'),d=Object.fromEntries(new FormData(f)),locations=$$('input[name="locations"]:checked',f).map(x=>x.value);const num=x=>x===''||x===undefined?null:Number(x);const captured=Date.parse(`${d.capturedAt}:00+05:00`);return {id:editingId||crypto.randomUUID(),schemaVersion:1,capturedAt:Number.isNaN(captured)?new Date().toISOString():new Date(captured).toISOString(),updatedAt:new Date().toISOString(),instrument:d.instrument.trim().toUpperCase(),session:d.session,direction:d.direction,scenario:d.scenario,locations,locationOther:d.locationOther?.trim()||'',cvd:{raw:num(d.cvdRaw),bucket:bucket(d.cvdRaw),relationship:d.relationship},structure:{cvd:d.cvdStructure||'',price:d.priceStructure||''},trd:{timeframe:d.trdTimeframe||'None',direction:d.trdDirection||'None',type:d.trdType||''},score:num(d.score),trade:{entry:num(d.entry),stop:num(d.stop),target:num(d.target),plannedRR:plannedRR({entry:d.entry,stop:d.stop,target:d.target}),result:d.result||'',resultR:num(d.resultR)},notes:{saw:d.saw?.trim()||'',why:d.why?.trim()||'',happened:d.happened?.trim()||'',learned:d.learned?.trim()||''},screenshots:photos,genie:{interpretation:null,userReview:null}}}
async function submitSetup(e){e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const setup=formPayload();const similar=setups.find(s=>s.id!==setup.id&&s.capturedAt===setup.capturedAt&&s.direction===setup.direction&&s.scenario===setup.scenario);if(similar&&!confirm('A setup with the same date/time, direction and scenario exists. Save this one anyway?'))return;try{await saveSetup(setup);clearTimeout(draftTimer);await clearDraft();localStorage.removeItem(draftKey);setups=await allSetups();notify(editingId?'Changes saved':'Setup saved locally');nav('library')}catch(err){notify(`Could not save: ${err.message}`)}}
async function deleteCurrent(id){if(!confirm('Delete this setup and its local screenshots? This cannot be undone.'))return;await removeSetup(id);setups=await allSetups();$('#detail-dialog').close();notify('Setup deleted');renderLibrary()}
function renderFilters(){const fs=['All','Long','Short','Reversal','Continuation'];$('#filters').innerHTML=fs.map(f=>`<button class="filter ${filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('');$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderLibrary()})}
function matching(){const q=$('#search').value.trim().toLowerCase();return setups.filter(s=>(filter==='All'||s.direction===filter||s.scenario===filter)&&(!q||[s.instrument,s.session,s.direction,s.scenario,...s.locations,s.locationOther,s.cvd?.relationship,s.notes?.saw,s.notes?.why,s.notes?.happened,s.notes?.learned].join(' ').toLowerCase().includes(q)))}
function renderLibrary(){renderFilters();const list=matching();$('#setup-list').innerHTML=list.length?list.map(s=>{const image=s.screenshots?.[0]?.blob;const url=image?URL.createObjectURL(image):'';const r=s.trade?.resultR;const result=s.trade?.result||'—';return `<article class="card" data-id="${s.id}"><div class="thumb">${url?`<img src="${url}" class="thumb" alt="Setup screenshot">`:'◫'}</div><div><div class="card-top"><span class="card-date">${pkt(s.capturedAt)}</span><span class="direction ${s.direction==='Short'?'short':''}">${esc(s.direction||'—')}</span></div><h3>${esc(s.scenario||'Setup')} <span class="card-date">· ${esc(s.session||'')}</span></h3><div class="card-meta">${esc(s.locations?.join(' · ')||'No locations')} · CVD ${esc(s.cvd?.bucket||bucket(s.cvd?.raw))}<br>${esc(s.cvd?.relationship||'')} · TRD ${esc(s.trd?.timeframe||'None')} ${esc(s.trd?.direction||'')}</div><div class="card-bottom"><span class="result ${result==='WIN'?'win':result==='LOSS'?'loss':''}">${esc(result)}</span><span class="r-value ${Number(r)>0?'positive':Number(r)<0?'danger-text':''}">${r==null?'—':`${Number(r)>0?'+':''}${r}R`}</span></div></div></article>`}).join(''):`<div class="empty"><strong>${setups.length?'No matches':'Your library starts here'}</strong>${setups.length?'Try another search or filter.':'Capture the setup, context and outcome while it is fresh.'}${setups.length?'':'<br><br><button class="primary compact" data-action="add">＋ Add your first setup</button>'}</div>`;$$('.card').forEach(c=>c.onclick=()=>showDetail(c.dataset.id));$$('[data-action="add"]').forEach(b=>b.onclick=()=>{renderForm();nav('add')})}
function textLine(label,value){return value?`<p><b>${esc(label)}:</b> ${esc(value)}</p>`:''}
function showDetail(id){const s=setups.find(x=>x.id===id);if(!s)return;const dlg=$('#detail-dialog');dlg.innerHTML=`<div class="dialog-inner"><div class="dialog-head"><div><p class="eyebrow">${esc(s.instrument||'XAUUSD')} · ${esc(s.session||'')}</p><h2>${esc(s.direction||'')} ${esc(s.scenario||'')}</h2><p class="card-date">${pkt(s.capturedAt)}</p></div><button class="close-button" aria-label="Close">×</button></div><div class="gallery">${(s.screenshots||[]).map(p=>`<img src="${URL.createObjectURL(p.blob)}" alt="Setup screenshot">`).join('')}</div><div class="detail-block"><h4>LOCATIONS</h4><p>${esc(s.locations?.join(' · ')||'—')} ${esc(s.locationOther||'')}</p></div><div class="detail-block"><h4>PRICE + CVD</h4>${textLine('Raw CVD',s.cvd?.raw)}${textLine('Bucket',s.cvd?.bucket)}${textLine('Relationship',s.cvd?.relationship)}${textLine('15m structure',`CVD ${s.structure?.cvd||'—'} · Price ${s.structure?.price||'—'}`)}</div><div class="detail-block"><h4>TRD / TRADE PLAN</h4>${textLine('TRD',`${s.trd?.timeframe||'None'} ${s.trd?.direction||''} · ${s.trd?.type||'—'}`)}${textLine('Plan',`Entry ${s.trade?.entry??'—'} · Stop ${s.trade?.stop??'—'} · Target ${s.trade?.target??'—'} · ${s.trade?.plannedRR||'—'} planned`)}${textLine('Result',`${s.trade?.result||'—'} · ${s.trade?.resultR??'—'}R`)}</div><div class="detail-block"><h4>NOTES</h4>${textLine('What I saw',s.notes?.saw)}${textLine('Why I entered',s.notes?.why)}${textLine('What happened',s.notes?.happened)}${textLine('What I learned',s.notes?.learned)}</div><div class="dialog-actions"><button class="secondary" id="edit-detail">Edit setup</button><button class="secondary danger-text" id="remove-detail">Delete</button></div></div>`;$('.close-button',dlg).onclick=()=>dlg.close();$('#edit-detail').onclick=()=>{dlg.close();renderForm(s);nav('add')};$('#remove-detail').onclick=()=>deleteCurrent(s.id);dlg.showModal()}
function groupedStats(keyFn){const map=new Map();for(const s of setups){const keys=keyFn(s);for(const key of(Array.isArray(keys)?keys:[keys]).filter(Boolean)){if(!map.has(key))map.set(key,{count:0,r:0,closed:0,wins:0});const a=map.get(key);a.count++;const result=s.trade?.result;if(['WIN','LOSS','BE'].includes(result)){a.closed++;a.r+=Number(s.trade?.resultR)||0;if(result==='WIN')a.wins++}}}return [...map].sort((a,b)=>b[1].count-a[1].count)}
function statBars(title,rows){const max=Math.max(1,...rows.map(([,d])=>d.count));return `<div class="panel stat-panel"><h3>${title}</h3>${rows.length?rows.slice(0,8).map(([name,d])=>`<div class="bar-row"><span>${esc(name)}</span><div class="bar"><i style="width:${Math.max(5,100*d.count/max)}%"></i></div><span>${d.closed?`${(d.r>=0?'+':'')+d.r.toFixed(1)}R`:`${d.count}`}</span></div>`).join(''):'<p class="card-date">No setups yet</p>'}</div>`}
function renderStats(){const closed=setups.filter(s=>['WIN','LOSS','BE'].includes(s.trade?.result));const wins=closed.filter(s=>s.trade.result==='WIN').length;const totalR=closed.reduce((n,s)=>n+(Number(s.trade.resultR)||0),0);const avg=closed.length?totalR/closed.length:0;const breakdown=['WIN','LOSS','BE','NO TRADE'].map(k=>[k,setups.filter(s=>s.trade?.result===k).length]);const metric=(label,value,cls='')=>`<div class="metric"><span>${label}</span><strong class="${cls}">${value}</strong></div>`;$('#stats-content').innerHTML=`<div class="stats-grid">${metric('Total setups',setups.length)}${metric('Win rate',closed.length?`${Math.round(wins/closed.length*100)}%`:'—')}${metric('Total R',`${totalR>=0?'+':''}${totalR.toFixed(1)}R`,totalR>=0?'positive':'negative')}${metric('Average R',closed.length?`${avg>=0?'+':''}${avg.toFixed(2)}R`:'—',avg>=0?'positive':'negative')}</div><div class="panel stat-panel"><h3>Results breakdown</h3>${breakdown.map(([label,count])=>`<div class="bar-row"><span>${label}</span><div class="bar"><i style="width:${setups.length?100*count/setups.length:0}%"></i></div><span>${count}</span></div>`).join('')}</div>${statBars('By location',groupedStats(s=>s.locations?.length?s.locations:['Unspecified']))}${statBars('By CVD relationship',groupedStats(s=>s.cvd?.relationship))}${statBars('By TRD timeframe',groupedStats(s=>s.trd?.timeframe))}${statBars('By scenario',groupedStats(s=>s.scenario))}`}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csvExport(){const columns=['id','capturedAt','instrument','session','direction','scenario','locations','locationOther','cvdRaw','cvdBucket','cvdRelationship','cvdStructure15m','priceStructure15m','trdTimeframe','trdDirection','trdType','score','entry','stop','target','plannedRR','result','resultR','saw','why','happened','learned'];const rows=setups.map(s=>[s.id,s.capturedAt,s.instrument,s.session,s.direction,s.scenario,(s.locations||[]).join('|'),s.locationOther,s.cvd?.raw,s.cvd?.bucket,s.cvd?.relationship,s.structure?.cvd,s.structure?.price,s.trd?.timeframe,s.trd?.direction,s.trd?.type,s.score,s.trade?.entry,s.trade?.stop,s.trade?.target,s.trade?.plannedRR,s.trade?.result,s.trade?.resultR,s.notes?.saw,s.notes?.why,s.notes?.happened,s.notes?.learned]);const quote=v=>`"${String(v??'').replace(/"/g,'""')}"`;download(new Blob(['\ufeff'+[columns,...rows].map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),`xau-library-${new Date().toISOString().slice(0,10)}.csv`)}
function validateBackup(data){if(!data||data.format!=='xau-library-backup'||data.version!==1||!Array.isArray(data.setups))throw new Error('Unsupported backup format');if(data.setups.length>10000)throw new Error('Backup has too many setups');const ids=new Set();for(const s of data.setups){if(!s||typeof s!=='object'||typeof s.id!=='string'||!s.id||ids.has(s.id)||typeof s.capturedAt!=='string'||Number.isNaN(Date.parse(s.capturedAt)))throw new Error('Backup contains an invalid or duplicate setup');ids.add(s.id);if(s.screenshots&&!Array.isArray(s.screenshots))throw new Error('Invalid screenshots');for(const p of s.screenshots||[])if(!(p.blob instanceof Blob))throw new Error('Backup screenshot data is invalid');if(s.locations&&!Array.isArray(s.locations))throw new Error('Invalid locations');if(s.trade?.resultR!=null&&!Number.isFinite(Number(s.trade.resultR)))throw new Error('Invalid result R value')}return data.setups}
function blobData(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
function dataBlob(data){const match=/^data:([^;,]+);base64,([\s\S]*)$/.exec(data);if(!match)throw new Error('Invalid screenshot encoding');const raw=atob(match[2]),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return new Blob([bytes],{type:match[1]})}
async function exportBackup(){const exported=[];for(const s of setups)exported.push({...s,screenshots:await Promise.all((s.screenshots||[]).map(async p=>({name:p.name,type:p.type,addedAt:p.addedAt,data:await blobData(p.blob)})))});const data={format:'xau-library-backup',version:1,exportedAt:new Date().toISOString(),timezone:'Asia/Karachi',setups:exported};download(new Blob([JSON.stringify(data)],{type:'application/json'}),`xau-library-backup-${new Date().toISOString().slice(0,10)}.json`);notify('Backup exported')}
async function importBackup(file){try{const data=JSON.parse(await file.text());const raw=data.setups;if(!Array.isArray(raw))throw new Error('Backup is missing setups');for(const s of raw)if(s.screenshots)for(const p of s.screenshots)if(p.blob===undefined&&typeof p.data==='string')p.blob=dataBlob(p.data);const next=validateBackup(data);if(!confirm(`Restore ${next.length} setups? This replaces all setups currently stored on this device.`))return;await replaceAll(next);setups=await allSetups();notify(`Restored ${setups.length} setups`);renderLibrary()}catch(e){alert(`Backup was not imported. ${e.message}`)}finally{$('#restore-file').value=''}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){const view=b.dataset.view;if(view==='add')renderForm();nav(view)}});
$('#search').addEventListener('input',renderLibrary);
$('#backup-json').onclick=exportBackup;$('#export-csv').onclick=csvExport;$('#restore-json').onclick=()=>$('#restore-file').click();$('#restore-file').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);
async function requestStorageProtection(){const badge=$('#storage-status'),detail=$('#storage-detail');try{if(!navigator.storage?.persisted){badge.textContent='Browser managed';detail.textContent='This browser does not offer persistent-storage protection here. Keep JSON backups somewhere other than this laptop.';return}let protectedStorage=await navigator.storage.persisted();if(!protectedStorage&&navigator.storage.persist)protectedStorage=await navigator.storage.persist();badge.textContent=protectedStorage?'Protected':'Browser managed';badge.classList.toggle('good',protectedStorage);detail.textContent=protectedStorage?'The browser granted storage protection against automatic eviction. Manual site-data clearing, profile removal, device damage or loss can still remove data; keep JSON backups elsewhere.':'The browser may automatically clear this site under storage pressure. Keep JSON backups somewhere other than this laptop.'}catch{badge.textContent='Browser managed';detail.textContent='Storage protection could not be confirmed. Keep JSON backups somewhere other than this laptop.'}}
async function init(){try{setups=await allSetups();renderLibrary();requestStorageProtection();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(e){$('#setup-list').innerHTML=`<div class="empty"><strong>Local storage unavailable</strong>${esc(e.message)}. Please open this app in a browser with IndexedDB enabled.</div>`}}
init();
